import mysql.connector

if __name__ == '__main__':
    mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        password="root",
        database="biu_shoes",
        port='3307',
    )
    cursor = mydb.cursor()
    # The finance team wants a high-level summary of sales for each shoe to evaluate product performance.
    # They need a summary that shows the total revenue generated by each shoe, across all orders.
    # Write a query to create a view (total sales per shoe) summarizing total sales per shoe,
    # including the shoe ID, name, and total revenue.
    # Write another query to display the entire view data.
    query = """
CREATE VIEW total_sales_per_shoe AS
    SELECT s.shoe_id, s.shoe_name, COUNT(os.shoe_id) * s.price AS total_revenue
    FROM shoe AS s
    JOIN order_shoe AS os
        ON s.shoe_id = os.shoe_id
    GROUP BY s.shoe_id, s.shoe_name, s.price;
-- The query to show the info of the view is in q11_2.py file
    """
    cursor.execute(query)
    print(', '.join(str(row) for row in cursor.fetchall()))